import { GameData } from "./mainText";

export const gamesData: GameData[] = [
  {
    matchNumber: 38,
    roundNumber: 1,
    date: "26/10/2025 18:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Charlotte Hornets",
    result: "113 - 139",
  },
  {
    matchNumber: 54,
    roundNumber: 2,
    date: "28/10/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Philadelphia 76ers",
    result: "134 - 139",
  },
  {
    matchNumber: 84,
    roundNumber: 2,
    date: "01/11/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Orlando Magic",
    result: "94 - 125",
  },
  {
    matchNumber: 123,
    roundNumber: 3,
    date: "07/11/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Cleveland Cavaliers",
    result: "114 - 148",
  },
  {
    matchNumber: 133,
    roundNumber: 3,
    date: "08/11/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Dallas Mavericks",
    result: "105 - 111",
  },
  {
    matchNumber: 194,
    roundNumber: 4,
    date: "16/11/2025 18:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Brooklyn Nets",
    result: "106 - 129",
  },
  {
    matchNumber: 261,
    roundNumber: 6,
    date: "25/11/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Atlanta Hawks",
    result: "132 - 113",
  },
  {
    matchNumber: 302,
    roundNumber: 6,
    date: "01/12/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Milwaukee Bucks",
    result: "129 - 126",
  },
  {
    matchNumber: 325,
    roundNumber: 7,
    date: "04/12/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Boston Celtics",
    result: "101 - 146",
  },
  {
    matchNumber: 342,
    roundNumber: 7,
    date: "06/12/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Atlanta Hawks",
    result: "116 - 131",
  },
  {
    matchNumber: 1212,
    roundNumber: 7,
    date: "12/12/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Cleveland Cavaliers",
    result: "126 - 130",
  },
  {
    matchNumber: 390,
    roundNumber: 8,
    date: "21/12/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "San Antonio Spurs",
    result: "113 - 124",
  },
  {
    matchNumber: 421,
    roundNumber: 9,
    date: "26/12/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Toronto Raptors",
    result: "138 - 117",
  },
  {
    matchNumber: 439,
    roundNumber: 9,
    date: "28/12/2025 18:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Memphis Grizzlies",
    result: "116 - 112",
  },
  {
    matchNumber: 444,
    roundNumber: 9,
    date: "29/12/2025 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Phoenix Suns",
    result: "101 - 115",
  },
  {
    matchNumber: 473,
    roundNumber: 10,
    date: "02/01/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Nets",
    result: "",
  },
  {
    matchNumber: 494,
    roundNumber: 10,
    date: "04/01/2026 18:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Minnesota Timberwolves",
    result: "",
  },
  {
    matchNumber: 507,
    roundNumber: 10,
    date: "06/01/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Orlando Magic",
    result: "",
  },
  {
    matchNumber: 530,
    roundNumber: 11,
    date: "09/01/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "New Orleans Pelicans",
    result: "",
  },
  {
    matchNumber: 608,
    roundNumber: 12,
    date: "19/01/2026 15:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "LA Clippers",
    result: "",
  },
  {
    matchNumber: 629,
    roundNumber: 13,
    date: "22/01/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Denver Nuggets",
    result: "",
  },
  {
    matchNumber: 664,
    roundNumber: 13,
    date: "27/01/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Portland Trail Blazers",
    result: "",
  },
  {
    matchNumber: 681,
    roundNumber: 14,
    date: "29/01/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Milwaukee Bucks",
    result: "",
  },
  {
    matchNumber: 688,
    roundNumber: 14,
    date: "30/01/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Los Angeles Lakers",
    result: "",
  },
  {
    matchNumber: 707,
    roundNumber: 14,
    date: "01/02/2026 18:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Sacramento Kings",
    result: "",
  },
  {
    matchNumber: 718,
    roundNumber: 14,
    date: "03/02/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "New York Knicks",
    result: "",
  },
  {
    matchNumber: 758,
    roundNumber: 15,
    date: "08/02/2026 14:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Miami Heat",
    result: "",
  },
  {
    matchNumber: 795,
    roundNumber: 16,
    date: "19/02/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Indiana Pacers",
    result: "",
  },
  {
    matchNumber: 803,
    roundNumber: 16,
    date: "20/02/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Indiana Pacers",
    result: "",
  },
  {
    matchNumber: 822,
    roundNumber: 16,
    date: "22/02/2026 18:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Charlotte Hornets",
    result: "",
  },
  {
    matchNumber: 865,
    roundNumber: 17,
    date: "28/02/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Toronto Raptors",
    result: "",
  },
  {
    matchNumber: 879,
    roundNumber: 17,
    date: "02/03/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Houston Rockets",
    result: "",
  },
  {
    matchNumber: 900,
    roundNumber: 18,
    date: "05/03/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Utah Jazz",
    result: "",
  },
  {
    matchNumber: 984,
    roundNumber: 19,
    date: "16/03/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Golden State Warriors",
    result: "",
  },
  {
    matchNumber: 993,
    roundNumber: 19,
    date: "17/03/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Detroit Pistons",
    result: "",
  },
  {
    matchNumber: 1009,
    roundNumber: 20,
    date: "19/03/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Detroit Pistons",
    result: "",
  },
  {
    matchNumber: 1022,
    roundNumber: 20,
    date: "21/03/2026 17:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Oklahoma City Thunder",
    result: "",
  },
  {
    matchNumber: 1105,
    roundNumber: 22,
    date: "01/04/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Philadelphia 76ers",
    result: "",
  },
  {
    matchNumber: 1148,
    roundNumber: 22,
    date: "07/04/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Chicago Bulls",
    result: "",
  },
  {
    matchNumber: 1166,
    roundNumber: 23,
    date: "09/04/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Chicago Bulls",
    result: "",
  },
  {
    matchNumber: 1172,
    roundNumber: 23,
    date: "10/04/2026 19:00",
    location: "Capital One Arena",
    homeTeam: "Washington Wizards",
    awayTeam: "Miami Heat",
    result: "",
  },
];
